--
-- EthioFantasy Migration 005: 100 Championship Quiz Levels
-- Target: PostgreSQL 16
--
INSERT INTO quiz_levels (id, chapter_name, category_title, title, subtitle, icon_type, accent_color, required_stars)
VALUES
  (1, 'Beginner', 'FOOTBALL BASICS', 'Football Basics I', 'Foundations, team size and essential kickoff rules', 'ball', 'from-blue-600 to-indigo-600', 0),
  (2, 'Beginner', 'LAWS OF THE GAME', 'Rules & Laws of the Game I', 'Offside rules, restarts and throw-in laws', 'referee', 'from-sky-600 to-blue-700', 2),
  (3, 'Beginner', 'FIELD & DIMENSIONS', 'Pitch, Goals & Dimensions I', 'Pitch boundary lines and corner flags', 'pitch', 'from-emerald-600 to-teal-700', 4),
  (4, 'Beginner', 'SCORING & GOALS', 'Scoring & Great Goals I', 'Hat-tricks, braces and bicycle kicks', 'striker', 'from-amber-500 to-orange-600', 6),
  (5, 'Beginner', 'GUESS THE FOOTBALL PLAYER', 'Superstar Players I', 'Modern Ballon d''Or titans and top strikers', 'striker', 'from-blue-500 to-cyan-600', 8),
  (6, 'Beginner', 'GUESS THE CLUB', 'Clubs & Crests I', 'Famous European clubs and historic badges', 'shield', 'from-indigo-600 to-blue-800', 10),
  (7, 'Beginner', 'WORLD CUP HISTORY', 'FIFA World Cup I', 'Inaugural tournaments and early champions', 'trophy', 'from-amber-600 to-yellow-600', 12),
  (8, 'Beginner', 'CHAMPIONS LEAGUE', 'UEFA Champions League I', 'Real Madrid''s European dominance', 'crown', 'from-blue-700 to-slate-900', 14),
  (9, 'Beginner', 'PREMIER LEAGUE', 'English Premier League I', 'Sir Alex Ferguson and Manchester United supremacy', 'lion', 'from-purple-600 to-indigo-700', 16),
  (10, 'Beginner', 'LA LIGA LEGENDS', 'Spanish La Liga I', 'El Clásico: Real Madrid vs Barcelona battles', 'crown', 'from-rose-600 to-red-700', 18),
  (11, 'Beginner', 'SERIE A & CALCIO', 'Italian Serie A I', 'AC Milan''s Dutch masters and Maldini era', 'shield', 'from-blue-600 to-teal-700', 20),
  (12, 'Beginner', 'BUNDESLIGA STARS', 'German Bundesliga I', 'Bayern Munich dominance and Gerd Müller', 'shield', 'from-red-600 to-amber-600', 22),
  (13, 'Beginner', 'AFRICAN FOOTBALL', 'African Football & AFCON I', 'Africa Cup of Nations historic champions', 'trophy', 'from-emerald-600 to-green-700', 24),
  (14, 'Beginner', 'ETHIOPIAN FOOTBALL', 'Ethiopian Football & Walia I', 'Ethiopia''s historic 1962 AFCON championship', 'lion', 'from-green-600 via-yellow-500 to-red-600', 26),
  (15, 'Beginner', 'MANAGERS & TACTICS', 'Legendary Managers I', 'Pep Guardiola''s Tiki-Taka and tactical revolution', 'referee', 'from-slate-700 to-slate-900', 28),
  (16, 'Beginner', 'INTERNATIONAL FOOTBALL', 'International Tournaments I', 'UEFA European Championships and Greece 2004', 'trophy', 'from-blue-600 to-indigo-800', 30),
  (17, 'Beginner', 'DEFENSE & KEEPERS', 'Goalkeepers & Defense I', 'Lev Yashin, Dino Zoff and Gianluigi Buffon', 'shield', 'from-cyan-600 to-blue-700', 32),
  (18, 'Beginner', 'RECORDS & AWARDS', 'Football Records & Awards I', 'Ballon d''Or history and multiple winners', 'trophy', 'from-amber-500 to-yellow-600', 34),
  (19, 'Beginner', 'WORLD STADIUMS', 'Stadiums & Cathedrals I', 'Wembley, Maracanã and Santiago Bernabéu', 'pitch', 'from-teal-600 to-slate-800', 36),
  (20, 'Beginner', 'EXPERT FOOTBALL QUIZ', 'Mixed Expert Trivia I', 'Hardcore trivia for the ultimate football minds', 'ball', 'from-indigo-600 to-purple-800', 38),
  (21, 'Amateur', 'FOOTBALL BASICS', 'Football Basics II', 'Passing, movement and ball control fundamentals', 'ball', 'from-blue-600 to-indigo-600', 40),
  (22, 'Amateur', 'LAWS OF THE GAME', 'Rules & Laws of the Game II', 'Free kicks, drop balls and advantage play', 'referee', 'from-sky-600 to-blue-700', 42),
  (23, 'Amateur', 'FIELD & DIMENSIONS', 'Pitch, Goals & Dimensions II', '18-yard box, penalty spot and goal area', 'pitch', 'from-emerald-600 to-teal-700', 44),
  (24, 'Amateur', 'SCORING & GOALS', 'Scoring & Great Goals II', 'Panenka penalties and Olympic direct corners', 'striker', 'from-amber-500 to-orange-600', 46),
  (25, 'Amateur', 'GUESS THE FOOTBALL PLAYER', 'Superstar Players II', 'Midfield playmakers and dribbling magicians', 'striker', 'from-blue-500 to-cyan-600', 48),
  (26, 'Amateur', 'GUESS THE CLUB', 'Clubs & Crests II', 'South American and North American club giants', 'shield', 'from-indigo-600 to-blue-800', 50),
  (27, 'Amateur', 'WORLD CUP HISTORY', 'FIFA World Cup II', 'Brazil''s 5 titles and Pelé''s dynasty', 'trophy', 'from-amber-600 to-yellow-600', 52),
  (28, 'Amateur', 'CHAMPIONS LEAGUE', 'UEFA Champions League II', 'Iconic Istanbul 2005 and historic comebacks', 'crown', 'from-blue-700 to-slate-900', 54),
  (29, 'Amateur', 'PREMIER LEAGUE', 'English Premier League II', 'Arsenal''s 2003-04 Unbeaten Invincibles', 'lion', 'from-purple-600 to-indigo-700', 56),
  (30, 'Amateur', 'LA LIGA LEGENDS', 'Spanish La Liga II', 'Messi, Cristiano Ronaldo and the 100-point seasons', 'crown', 'from-rose-600 to-red-700', 58),
  (31, 'Amateur', 'SERIE A & CALCIO', 'Italian Serie A II', 'Juventus scudetto streaks and Del Piero', 'shield', 'from-blue-600 to-teal-700', 60),
  (32, 'Amateur', 'BUNDESLIGA STARS', 'German Bundesliga II', 'Borussia Dortmund, Klopp and the Yellow Wall', 'shield', 'from-red-600 to-amber-600', 62),
  (33, 'Amateur', 'AFRICAN FOOTBALL', 'African Football & AFCON II', 'George Weah, Samuel Eto''o and Didier Drogba', 'trophy', 'from-emerald-600 to-green-700', 64),
  (34, 'Amateur', 'ETHIOPIAN FOOTBALL', 'Ethiopian Football & Walia II', 'Saint George SC (Kidus Giorgis) record titles', 'lion', 'from-green-600 via-yellow-500 to-red-600', 66),
  (35, 'Amateur', 'MANAGERS & TACTICS', 'Legendary Managers II', 'José Mourinho, Jürgen Klopp and Carlo Ancelotti', 'referee', 'from-slate-700 to-slate-900', 68),
  (36, 'Amateur', 'INTERNATIONAL FOOTBALL', 'International Tournaments II', 'Copa América battles and Brazil vs Argentina', 'trophy', 'from-blue-600 to-indigo-800', 70),
  (37, 'Amateur', 'DEFENSE & KEEPERS', 'Goalkeepers & Defense II', 'Manuel Neuer''s sweeper-keeper revolution', 'shield', 'from-cyan-600 to-blue-700', 72),
  (38, 'Amateur', 'RECORDS & AWARDS', 'Football Records & Awards II', 'Most goals in a calendar year (Messi 91)', 'trophy', 'from-amber-500 to-yellow-600', 74),
  (39, 'Amateur', 'WORLD STADIUMS', 'Stadiums & Cathedrals II', 'Camp Nou, San Siro and Old Trafford', 'pitch', 'from-teal-600 to-slate-800', 76),
  (40, 'Amateur', 'EXPERT FOOTBALL QUIZ', 'Mixed Expert Trivia II', 'Bizarre football rules, quirks and rare events', 'ball', 'from-indigo-600 to-purple-800', 78),
  (41, 'Semi-Pro', 'FOOTBALL BASICS', 'Football Basics III', 'Match periods, substitutions and game flow', 'ball', 'from-blue-600 to-indigo-600', 80),
  (42, 'Semi-Pro', 'LAWS OF THE GAME', 'Rules & Laws of the Game III', 'Handball criteria and back-pass regulations', 'referee', 'from-sky-600 to-blue-700', 82),
  (43, 'Semi-Pro', 'FIELD & DIMENSIONS', 'Pitch, Goals & Dimensions III', 'Crossbar heights, goal widths and pitch surface', 'pitch', 'from-emerald-600 to-teal-700', 84),
  (44, 'Semi-Pro', 'SCORING & GOALS', 'Scoring & Great Goals III', 'Volleys, trivelas and outside-foot strikes', 'striker', 'from-amber-500 to-orange-600', 86),
  (45, 'Semi-Pro', 'GUESS THE FOOTBALL PLAYER', 'Superstar Players III', 'Legendary icons of the 70s, 80s and 90s', 'striker', 'from-blue-500 to-cyan-600', 88),
  (46, 'Semi-Pro', 'GUESS THE CLUB', 'Clubs & Crests III', 'Nicknames, colors and founding histories', 'shield', 'from-indigo-600 to-blue-800', 90),
  (47, 'Semi-Pro', 'WORLD CUP HISTORY', 'FIFA World Cup III', 'Maradona 1986, France 1998 and Germany 2014', 'trophy', 'from-amber-600 to-yellow-600', 92),
  (48, 'Semi-Pro', 'CHAMPIONS LEAGUE', 'UEFA Champions League III', 'Treble winners and dominant dynasties', 'crown', 'from-blue-700 to-slate-900', 94),
  (49, 'Semi-Pro', 'PREMIER LEAGUE', 'English Premier League III', 'Manchester City''s Centurions and Haaland records', 'lion', 'from-purple-600 to-indigo-700', 96),
  (50, 'Semi-Pro', 'LA LIGA LEGENDS', 'Spanish La Liga III', 'Atlético Madrid, Diego Simeone and Valencia', 'crown', 'from-rose-600 to-red-700', 98),
  (51, 'Semi-Pro', 'SERIE A & CALCIO', 'Italian Serie A III', 'Inter Milan''s 2010 Treble and Maradona''s Napoli', 'shield', 'from-blue-600 to-teal-700', 100),
  (52, 'Semi-Pro', 'BUNDESLIGA STARS', 'German Bundesliga III', 'Der Klassiker and German tactical precision', 'shield', 'from-red-600 to-amber-600', 102),
  (53, 'Semi-Pro', 'AFRICAN FOOTBALL', 'African Football & AFCON III', 'Senegal, Cameroon and Nigeria World Cup feats', 'trophy', 'from-emerald-600 to-green-700', 104),
  (54, 'Semi-Pro', 'ETHIOPIAN FOOTBALL', 'Ethiopian Football & Walia III', 'Ethiopian Coffee SC (Bunna) and Sheger derbies', 'lion', 'from-green-600 via-yellow-500 to-red-600', 106),
  (55, 'Semi-Pro', 'MANAGERS & TACTICS', 'Legendary Managers III', 'Arrigo Sacchi, Rinus Michels and Total Football', 'referee', 'from-slate-700 to-slate-900', 108),
  (56, 'Semi-Pro', 'INTERNATIONAL FOOTBALL', 'International Tournaments III', 'CECAFA Senior Challenge Cup in East Africa', 'trophy', 'from-blue-600 to-indigo-800', 110),
  (57, 'Semi-Pro', 'DEFENSE & KEEPERS', 'Goalkeepers & Defense III', 'Clean sheet records and penalty savers', 'shield', 'from-cyan-600 to-blue-700', 112),
  (58, 'Semi-Pro', 'RECORDS & AWARDS', 'Football Records & Awards III', 'Fastest goals and longest unbeaten streaks', 'trophy', 'from-amber-500 to-yellow-600', 114),
  (59, 'Semi-Pro', 'WORLD STADIUMS', 'Stadiums & Cathedrals III', 'Addis Ababa Stadium and historic African arenas', 'pitch', 'from-teal-600 to-slate-800', 116),
  (60, 'Semi-Pro', 'EXPERT FOOTBALL QUIZ', 'Mixed Expert Trivia III', 'Jersey numbers, mascots and football culture', 'ball', 'from-indigo-600 to-purple-800', 118),
  (61, 'Professional', 'FOOTBALL BASICS', 'Football Basics IV', 'Positions, jerseys and standard equipment', 'ball', 'from-blue-600 to-indigo-600', 120),
  (62, 'Professional', 'LAWS OF THE GAME', 'Rules & Laws of the Game IV', 'Penalty box regulations and goal kicks', 'referee', 'from-sky-600 to-blue-700', 122),
  (63, 'Professional', 'FIELD & DIMENSIONS', 'Pitch, Goals & Dimensions IV', 'Center circle, technical areas and stadiums', 'pitch', 'from-emerald-600 to-teal-700', 124),
  (64, 'Professional', 'SCORING & GOALS', 'Scoring & Great Goals IV', 'Long-range thunderbolts and solo runs', 'striker', 'from-amber-500 to-orange-600', 126),
  (65, 'Professional', 'GUESS THE FOOTBALL PLAYER', 'Superstar Players IV', 'Golden Boot winners and continental stars', 'striker', 'from-blue-500 to-cyan-600', 128),
  (66, 'Professional', 'GUESS THE CLUB', 'Clubs & Crests IV', 'Club derbies, rivalries and city battles', 'shield', 'from-indigo-600 to-blue-800', 130),
  (67, 'Professional', 'WORLD CUP HISTORY', 'FIFA World Cup IV', 'Qatar 2022, Messi and modern drama', 'trophy', 'from-amber-600 to-yellow-600', 132),
  (68, 'Professional', 'CHAMPIONS LEAGUE', 'UEFA Champions League IV', 'Record goalscorers and knockout thrillers', 'crown', 'from-blue-700 to-slate-900', 134),
  (69, 'Professional', 'PREMIER LEAGUE', 'English Premier League IV', 'Golden Boot icons and Premier League derbies', 'lion', 'from-purple-600 to-indigo-700', 136),
  (70, 'Professional', 'LA LIGA LEGENDS', 'Spanish La Liga IV', 'Pichichi winners and Spanish football lore', 'crown', 'from-rose-600 to-red-700', 138),
  (71, 'Professional', 'SERIE A & CALCIO', 'Italian Serie A IV', 'Catennacio, defending gods and Capocannoniere', 'shield', 'from-blue-600 to-teal-700', 140),
  (72, 'Professional', 'BUNDESLIGA STARS', 'German Bundesliga IV', 'Bayer Leverkusen''s undefeated 2023-24 season', 'shield', 'from-red-600 to-amber-600', 142),
  (73, 'Professional', 'AFRICAN FOOTBALL', 'African Football & AFCON IV', 'Mohamed Salah, Sadio Mané and African stars', 'trophy', 'from-emerald-600 to-green-700', 144),
  (74, 'Professional', 'ETHIOPIAN FOOTBALL', 'Ethiopian Football & Walia IV', 'Walia Ibex national stars and Saladin Said', 'lion', 'from-green-600 via-yellow-500 to-red-600', 146),
  (75, 'Professional', 'MANAGERS & TACTICS', 'Legendary Managers IV', 'Johan Cruyff, Bielsa and tactical formations', 'referee', 'from-slate-700 to-slate-900', 148),
  (76, 'Professional', 'INTERNATIONAL FOOTBALL', 'International Tournaments IV', 'Olympic Football tournaments and Asian Cup', 'trophy', 'from-blue-600 to-indigo-800', 150),
  (77, 'Professional', 'DEFENSE & KEEPERS', 'Goalkeepers & Defense IV', 'Baresi, Maldini, Sergio Ramos and Van Dijk', 'shield', 'from-cyan-600 to-blue-700', 152),
  (78, 'Professional', 'RECORDS & AWARDS', 'Football Records & Awards IV', 'FIFA Puskás Award and wonder strikes', 'trophy', 'from-amber-500 to-yellow-600', 154),
  (79, 'Professional', 'WORLD STADIUMS', 'Stadiums & Cathedrals IV', 'Atmosphere, capacities and stadium architecture', 'pitch', 'from-teal-600 to-slate-800', 156),
  (80, 'Professional', 'EXPERT FOOTBALL QUIZ', 'Mixed Expert Trivia IV', 'Transfer sagas and historic milestone moments', 'ball', 'from-indigo-600 to-purple-800', 158),
  (81, 'World Class', 'FOOTBALL BASICS', 'Football Basics V', 'Mastery of core football fundamentals', 'ball', 'from-blue-600 to-indigo-600', 160),
  (82, 'World Class', 'LAWS OF THE GAME', 'Rules & Laws of the Game V', 'Expert IFAB laws and refereeing decisions', 'referee', 'from-sky-600 to-blue-700', 162),
  (83, 'World Class', 'FIELD & DIMENSIONS', 'Pitch, Goals & Dimensions V', 'Pitch geometry and FIFA specifications', 'pitch', 'from-emerald-600 to-teal-700', 164),
  (84, 'World Class', 'SCORING & GOALS', 'Scoring & Great Goals V', 'Legendary World Cup and Champions League goals', 'striker', 'from-amber-500 to-orange-600', 166),
  (85, 'World Class', 'GUESS THE FOOTBALL PLAYER', 'Superstar Players V', 'All-time football legends and Hall of Famers', 'striker', 'from-blue-500 to-cyan-600', 168),
  (86, 'World Class', 'GUESS THE CLUB', 'Clubs & Crests V', 'World club champions and badge recognition', 'shield', 'from-indigo-600 to-blue-800', 170),
  (87, 'World Class', 'WORLD CUP HISTORY', 'FIFA World Cup V', 'World Cup records, golden boots and finals', 'trophy', 'from-amber-600 to-yellow-600', 172),
  (88, 'World Class', 'CHAMPIONS LEAGUE', 'UEFA Champions League V', 'Finals lore, records and anthem history', 'crown', 'from-blue-700 to-slate-900', 174),
  (89, 'World Class', 'PREMIER LEAGUE', 'English Premier League V', 'Underdog miracles, Leicester 2016 and records', 'lion', 'from-purple-600 to-indigo-700', 176),
  (90, 'World Class', 'LA LIGA LEGENDS', 'Spanish La Liga V', 'Historic European dominance and Galácticos', 'crown', 'from-rose-600 to-red-700', 178),
  (91, 'World Class', 'SERIE A & CALCIO', 'Italian Serie A V', 'Serie A Golden Age and derby rivalries', 'shield', 'from-blue-600 to-teal-700', 180),
  (92, 'World Class', 'BUNDESLIGA STARS', 'German Bundesliga V', 'Bundesliga record goals, stadiums and fans', 'shield', 'from-red-600 to-amber-600', 182),
  (93, 'World Class', 'AFRICAN FOOTBALL', 'African Football & AFCON V', 'CAF Champions League and continental legends', 'trophy', 'from-emerald-600 to-green-700', 184),
  (94, 'World Class', 'ETHIOPIAN FOOTBALL', 'Ethiopian Football & Walia V', 'Addis Ababa Stadium, Fasil Kenema and legends', 'lion', 'from-green-600 via-yellow-500 to-red-600', 186),
  (95, 'World Class', 'MANAGERS & TACTICS', 'Legendary Managers V', 'Trophy kings and master strategists', 'referee', 'from-slate-700 to-slate-900', 188),
  (96, 'World Class', 'INTERNATIONAL FOOTBALL', 'International Tournaments V', 'Continental showdowns and golden generations', 'trophy', 'from-blue-600 to-indigo-800', 190),
  (97, 'World Class', 'DEFENSE & KEEPERS', 'Goalkeepers & Defense V', 'Defensive walls, tackles and clean sheet kings', 'shield', 'from-cyan-600 to-blue-700', 192),
  (98, 'World Class', 'RECORDS & AWARDS', 'Football Records & Awards V', 'All-time appearances, caps and transfers', 'trophy', 'from-amber-500 to-yellow-600', 194),
  (99, 'World Class', 'WORLD STADIUMS', 'Stadiums & Cathedrals V', 'Iconic host venues of historic World Cup finals', 'pitch', 'from-teal-600 to-slate-800', 196),
  (100, 'World Class', 'EXPERT FOOTBALL QUIZ', 'Mixed Expert Trivia V', 'Grand championship test of football intellect', 'ball', 'from-indigo-600 to-purple-800', 198)
ON CONFLICT (id) DO UPDATE SET
  chapter_name = EXCLUDED.chapter_name,
  category_title = EXCLUDED.category_title,
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  icon_type = EXCLUDED.icon_type,
  accent_color = EXCLUDED.accent_color,
  required_stars = EXCLUDED.required_stars;
