import { QuestionImage, QuizQuestion } from '../../types';

export const INITIAL_IMAGE_LIBRARY: QuestionImage[] = [
  {
    id: 'img-1',
    url: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=600&q=80',
    title: 'Modern Football Stadium at Night',
    altText: 'Illuminated professional football stadium with packed crowd',
    category: 'STADIUMS',
    dimensions: '1920x1080',
    fileSize: '1.2 MB',
    usageCount: 14,
    tags: ['stadium', 'night', 'arena', 'champions league', 'premier league'],
    credit: 'Unsplash Sports Media',
    uploadedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'img-2',
    url: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=600&q=80',
    title: 'Match Ball on Pitch Grass',
    altText: 'Classic football match ball on pristine manicured grass turf',
    category: 'MATCHES',
    dimensions: '1600x1200',
    fileSize: '890 KB',
    usageCount: 18,
    tags: ['ball', 'grass', 'pitch', 'kickoff', 'equipment'],
    credit: 'Unsplash Sports',
    uploadedAt: '2026-09-02T10:30:00Z',
  },
  {
    id: 'img-3',
    url: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=600&q=80',
    title: 'Golden Championship Trophy',
    altText: 'Gold tournament trophy gleaming on pedestal under arena spotlight',
    category: 'TROPHIES',
    dimensions: '2048x1536',
    fileSize: '1.8 MB',
    usageCount: 22,
    tags: ['trophy', 'world cup', 'gold', 'champions', 'winner', 'cup'],
    credit: 'FIFA Heritage Archives',
    uploadedAt: '2026-09-03T14:15:00Z',
  },
  {
    id: 'img-4',
    url: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=600&q=80',
    title: 'Striker Taking Penalty Kick',
    altText: 'Football player focused on ball right before penalty strike',
    category: 'PLAYERS',
    dimensions: '1920x1080',
    fileSize: '1.1 MB',
    usageCount: 9,
    tags: ['player', 'penalty', 'striker', 'boots', 'action'],
    credit: 'SportFoto International',
    uploadedAt: '2026-09-05T09:45:00Z',
  },
  {
    id: 'img-5',
    url: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=600&q=80',
    title: 'Addis Ababa Stadium Grandstand',
    altText: 'Historic Addis Ababa Stadium during a packed Ethiopian Premier League fixture',
    category: 'ETHIOPIAN',
    dimensions: '1800x1200',
    fileSize: '1.4 MB',
    usageCount: 12,
    tags: ['ethiopia', 'addis ababa', 'sheger derby', 'bunna', 'saint george', 'walia'],
    credit: 'EthioFootball Photo Archive',
    uploadedAt: '2026-09-06T11:20:00Z',
  },
  {
    id: 'img-6',
    url: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=600&q=80',
    title: 'Celebration Goal Moment',
    altText: 'Football team celebrating a winning goal in front of roaring supporters',
    category: 'MATCHES',
    dimensions: '2048x1365',
    fileSize: '1.6 MB',
    usageCount: 8,
    tags: ['celebration', 'goal', 'fans', 'supporters', 'team'],
    credit: 'Action Images',
    uploadedAt: '2026-09-07T16:00:00Z',
  },
  {
    id: 'img-7',
    url: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=600&q=80',
    title: 'Tactical Board and Whistle',
    altText: 'Coach tactical formation board with referee whistle and timer',
    category: 'GENERAL',
    dimensions: '1600x1067',
    fileSize: '950 KB',
    usageCount: 5,
    tags: ['tactics', 'coaching', 'referee', 'rules', 'formation'],
    credit: 'Football Strategy Lab',
    uploadedAt: '2026-09-08T13:10:00Z',
  },
  {
    id: 'img-8',
    url: 'https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?auto=format&fit=crop&w=600&q=80',
    title: 'Walia Ibex National Team Flag & Kit',
    altText: 'Green, yellow and red Ethiopian national team colors on jersey',
    category: 'ETHIOPIAN',
    dimensions: '1920x1280',
    fileSize: '1.3 MB',
    usageCount: 15,
    tags: ['walia', 'ethiopia', 'national team', 'afcon', 'jersey'],
    credit: 'Ethiopian Football Federation Media',
    uploadedAt: '2026-09-10T15:40:00Z',
  }
];

export const INITIAL_QUESTION_BANK: QuizQuestion[] = [
  {
    id: 'q-101',
    questionCode: 'Q000101',
    levelNumber: 1,
    orderNumber: 1,
    questionText: 'Which club holds the all-time record for the most Ethiopian Premier League titles?',
    questionAmharic: 'በኢትዮጵያ ፕሪሚየር ሊግ ታሪክ ውስጥ በርካታ ዋንጫዎችን ያነሳው ክለብ የትኛው ነው?',
    options: ['Saint George SC (Kidus Giorgis)', 'Ethiopian Coffee SC (Bunna)', 'Fasil Kenema SC', 'Hawassa City SC'],
    correctOptionIndex: 0,
    difficulty: 'EASY',
    category: 'Ethiopian Football',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Historic Addis Ababa stadium during derby match',
    sourceReference: 'Ethiopian Premier League Official Records 2024',
    explanation: 'Saint George SC has won over 30 top-flight domestic championship titles, making them the most successful Ethiopian club.',
    createdAt: '2026-08-15T09:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-102',
    questionCode: 'Q000102',
    levelNumber: 1,
    orderNumber: 2,
    questionText: 'In what year did the Ethiopian national team (Walia Ibex) win the Africa Cup of Nations (AFCON)?',
    questionAmharic: 'ኢትዮጵያ የአፍሪካ ዋንጫን ያሸነፈችው በየትኛው ዓ.ም. ነው?',
    options: ['1957', '1962', '1976', '1984'],
    correctOptionIndex: 1,
    difficulty: 'EASY',
    category: 'AFCON',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: 'https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Ethiopian football national honors celebration',
    sourceReference: 'CAF Centennial History - 1962 Tournament in Addis Ababa',
    explanation: 'Ethiopia defeated Egypt 4-2 after extra time in the 1962 AFCON final played in Addis Ababa.',
    createdAt: '2026-08-15T09:15:00Z',
    updatedAt: '2026-09-20T10:15:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-103',
    questionCode: 'Q000103',
    levelNumber: 1,
    orderNumber: 3,
    questionText: 'What is the traditional name of the fierce capital derby between Saint George SC and Ethiopian Coffee SC?',
    questionAmharic: 'በቅዱስ ጊዮርጊስ እና በኢትዮጵያ ቡና መካከል የሚደረገው ታላቅ ደርቢ ምን ይባላል?',
    options: ['Sheger Derby', 'Great Rift Derby', 'Highland Clash', 'Awash Cup'],
    correctOptionIndex: 0,
    difficulty: 'EASY',
    category: 'Ethiopian Football',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: undefined, // NO IMAGE test
    imageAlt: undefined,
    sourceReference: 'Addis Ababa Football Association Gazette',
    explanation: 'The match between Saint George SC and Ethiopian Coffee SC is universally celebrated as the Sheger Derby.',
    createdAt: '2026-08-16T11:00:00Z',
    updatedAt: '2026-09-20T10:30:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-104',
    questionCode: 'Q000104',
    levelNumber: 1,
    orderNumber: 4,
    questionText: 'Which country won the inaugural FIFA Men\'s World Cup hosted in 1930?',
    questionAmharic: 'በ1930 የተካሄደውን የመጀመሪያውን የፊፋ የዓለም ዋንጫ ያሸነፈችው ሀገር የትኛዋ ናት?',
    options: ['Brazil', 'Argentina', 'Uruguay', 'Italy'],
    correctOptionIndex: 2,
    difficulty: 'EASY',
    category: 'World Cup',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Jules Rimet Cup and historic trophy representation',
    sourceReference: 'FIFA Archive - 1930 World Cup Finals Montevido',
    explanation: 'Uruguay defeated Argentina 4-2 in the final in Montevideo to become the first FIFA World Champions.',
    createdAt: '2026-08-16T12:00:00Z',
    updatedAt: '2026-09-20T10:45:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-105',
    questionCode: 'Q000105',
    levelNumber: 1,
    orderNumber: 5,
    questionText: 'Who was the top goalscorer in the 2022 FIFA World Cup in Qatar, receiving the Golden Boot?',
    questionAmharic: 'በ2022 የኳታር የዓለም ዋንጫ የወርቅ ጫማ ያሸነፈው ከፍተኛ ግብ አስቆጣሪ ማን ነበር?',
    options: ['Lionel Messi', 'Kylian Mbappé', 'Julián Álvarez', 'Olivier Giroud'],
    correctOptionIndex: 1,
    difficulty: 'EASY',
    category: 'World Cup',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'World Cup final match action shot',
    sourceReference: 'FIFA Technical Study Group 2022',
    explanation: 'Kylian Mbappé scored 8 goals including a hat-trick in the final against Argentina to claim the Golden Boot.',
    createdAt: '2026-08-17T08:00:00Z',
    updatedAt: '2026-09-20T11:00:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-106',
    questionCode: 'Q000106',
    levelNumber: 2,
    orderNumber: 1,
    questionText: 'Which club has won the most UEFA Champions League / European Cup titles in history?',
    questionAmharic: 'በአውሮፓ ሻምፒዮንስ ሊግ ታሪክ ውስጥ በርካታ ዋንጫዎችን ያነሳው ክለብ የትኛው ነው?',
    options: ['AC Milan', 'Real Madrid', 'Liverpool FC', 'Bayern Munich'],
    correctOptionIndex: 1,
    difficulty: 'EASY',
    category: 'Champions League',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'UEFA Champions League stadium atmosphere',
    sourceReference: 'UEFA Official Champions League Statistics Handbook',
    explanation: 'Real Madrid holds the outright record with 15 European Cup / UEFA Champions League titles.',
    createdAt: '2026-08-18T10:00:00Z',
    updatedAt: '2026-09-20T11:30:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-107',
    questionCode: 'Q000107',
    levelNumber: 2,
    orderNumber: 2,
    questionText: 'Which player holds the all-time scoring record in the English Premier League with 260 goals?',
    questionAmharic: 'በእንግሊዝ ፕሪሚየር ሊግ ታሪክ ውስጥ 260 ግቦችን በማስቆጠር የሁልጊዜ ከፍተኛ ጎል አስቆጣሪ ማን ነው?',
    options: ['Wayne Rooney', 'Alan Shearer', 'Harry Kane', 'Thierry Henry'],
    correctOptionIndex: 1,
    difficulty: 'MEDIUM',
    category: 'Premier League',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: undefined, // NO IMAGE test
    imageAlt: undefined,
    sourceReference: 'Premier League All-Time Milestone Records',
    explanation: 'Alan Shearer scored 260 Premier League goals playing for Blackburn Rovers and Newcastle United.',
    createdAt: '2026-08-19T14:20:00Z',
    updatedAt: '2026-09-20T12:00:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-108',
    questionCode: 'Q000108',
    levelNumber: 2,
    orderNumber: 3,
    questionText: 'Which African player won the prestigious Ballon d\'Or award in 1995?',
    questionAmharic: 'በ1995 የባሎን ዶር (Ballon d\'Or) ክብርን ያሸነፈው ብቸኛው አፍሪካዊ ተጫዋች ማን ነው?',
    options: ['George Weah', 'Didier Drogba', 'Samuel Eto\'o', 'Jay-Jay Okocha'],
    correctOptionIndex: 0,
    difficulty: 'MEDIUM',
    category: 'Players',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Historic Ballon d\'Or ceremony celebration',
    sourceReference: 'France Football Ballon d\'Or Archive 1995',
    explanation: 'Liberian forward George Weah made history in 1995 when playing for AC Milan and Paris Saint-Germain.',
    createdAt: '2026-08-20T09:30:00Z',
    updatedAt: '2026-09-20T12:30:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-109',
    questionCode: 'Q000109',
    levelNumber: 3,
    orderNumber: 1,
    questionText: 'Which national team won the Africa Cup of Nations (AFCON) three consecutive times between 2006 and 2010?',
    questionAmharic: 'ከ2006 እስከ 2010 ባለው ጊዜ ውስጥ የአፍሪካ ዋንጫን በተከታታይ ሦስት ጊዜ ያሸነፈችው ሀገር የትኛዋ ናት?',
    options: ['Cameroon', 'Ghana', 'Egypt', 'Nigeria'],
    correctOptionIndex: 2,
    difficulty: 'HARD',
    category: 'AFCON',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'AFCON gold trophy representation',
    sourceReference: 'CAF African Cup of Nations Finals Records',
    explanation: 'Egypt won the 2006, 2008, and 2010 AFCON tournaments under head coach Hassan Shehata.',
    createdAt: '2026-08-22T10:10:00Z',
    updatedAt: '2026-09-20T13:00:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-110',
    questionCode: 'Q000110',
    levelNumber: 3,
    orderNumber: 2,
    questionText: 'Who was the first African nation to reach the semi-finals of a FIFA Men\'s World Cup?',
    questionAmharic: 'በፊፋ የዓለም ዋንጫ ግማሽ ፍፃሜ የደረሰችው የመጀመሪያዋ አፍሪካዊት ሀገር ማን ናት?',
    options: ['Cameroon (1990)', 'Senegal (2002)', 'Ghana (2010)', 'Morocco (2022)'],
    correctOptionIndex: 3,
    difficulty: 'MEDIUM',
    category: 'World Cup',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: undefined, // NO IMAGE test
    imageAlt: undefined,
    sourceReference: 'FIFA World Cup Qatar 2022 Technical Report',
    explanation: 'Morocco made history in Qatar 2022 by defeating Portugal 1-0 in the quarter-finals to become the first African nation in the semi-finals.',
    createdAt: '2026-08-23T11:45:00Z',
    updatedAt: '2026-09-20T13:30:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-111',
    questionCode: 'Q000111',
    levelNumber: 37,
    orderNumber: 1,
    questionText: 'Which country won the 1974 FIFA World Cup as tournament hosts against Netherlands in the final?',
    questionAmharic: 'በ1974 የዓለም ዋንጫ አስተናጋጅ ሆና ኔዘርላንድስን በማሸነፍ ዋንጫውን ያነሳችው ሀገር ማን ናት?',
    options: ['West Germany', 'Brazil', 'Italy', 'Poland'],
    correctOptionIndex: 0,
    difficulty: 'HARD',
    category: 'World Cup',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Olympiastadion Munich historical match setting',
    sourceReference: 'FIFA World Cup 1974 Munich Report',
    explanation: 'West Germany captain Franz Beckenbauer lifted the new FIFA World Cup trophy after beating the Dutch 2-1.',
    createdAt: '2026-08-25T14:00:00Z',
    updatedAt: '2026-09-22T10:00:00Z',
    updatedBy: 'Selamawit Desta',
  },
  {
    id: 'q-112',
    questionCode: 'Q000112',
    levelNumber: 37,
    orderNumber: 2,
    questionText: 'Who scored the famous "Hand of God" and "Goal of the Century" against England in 1986?',
    questionAmharic: 'በ1986 በሜክሲኮ የዓለም ዋንጫ ላይ "የእግዚአብሔር እጅ" በመባል የሚታወቀውን ግብ ያስቆጠረው ተጫዋች ማን ነው?',
    options: ['Pelé', 'Diego Maradona', 'Mario Kempes', 'Zico'],
    correctOptionIndex: 1,
    difficulty: 'EASY',
    category: 'History',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Iconic football strike action in international game',
    sourceReference: 'FIFA Greatest World Cup Moments Anthology',
    explanation: 'Diego Armando Maradona scored both legendary goals in Argentina\'s 2-1 victory over England at the Azteca.',
    createdAt: '2026-08-25T14:30:00Z',
    updatedAt: '2026-09-22T10:30:00Z',
    updatedBy: 'Selamawit Desta',
  },

  // Daily Challenge Pool Questions
  {
    id: 'q-201',
    questionCode: 'Q000201',
    orderNumber: 1,
    questionText: 'Which manager won the English Premier League with Leicester City in the 2015-16 fairytale season?',
    questionAmharic: 'በ2015-16 የውድድር ዘመን ሌስተር ሲቲን ያልተጠበቀ የፕሪሚየር ሊግ ሻምፒዮን ያደረገው አሰልጣኝ ማን ነው?',
    options: ['Nigel Pearson', 'Claudio Ranieri', 'Brendan Rodgers', 'Roberto Mancini'],
    correctOptionIndex: 1,
    difficulty: 'MEDIUM',
    category: 'Premier League',
    status: 'PUBLISHED',
    pool: 'DAILY_CHALLENGE',
    imageUrl: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Tactics and coaching equipment representation',
    sourceReference: 'Premier League Season 2015-16 Review',
    explanation: 'Claudio Ranieri guided 5000-to-1 outsiders Leicester City to their historic first top-flight title.',
    createdAt: '2026-08-28T09:00:00Z',
    updatedAt: '2026-09-23T08:15:00Z',
    updatedBy: 'Dawit Mengistu',
  },
  {
    id: 'q-202',
    questionCode: 'Q000202',
    orderNumber: 2,
    questionText: 'In what year was the Ethiopian Premier League officially founded under its modern professional format?',
    questionAmharic: 'የኢትዮጵያ ፕሪሚየር ሊግ በዘመናዊ ቅርፁ በየትኛው ዓ.ም. ተመሰረተ?',
    options: ['1997', '2001', '1990', '2005'],
    correctOptionIndex: 0,
    difficulty: 'HARD',
    category: 'Ethiopian Football',
    status: 'PUBLISHED',
    pool: 'DAILY_CHALLENGE',
    imageUrl: undefined, // NO IMAGE test
    imageAlt: undefined,
    sourceReference: 'Ethiopian Football Federation Almanac',
    explanation: 'The modern Ethiopian Premier League kicked off in 1997-98 replacing the former First Division championship.',
    createdAt: '2026-08-29T10:00:00Z',
    updatedAt: '2026-09-23T08:45:00Z',
    updatedBy: 'Dawit Mengistu',
  },
  {
    id: 'q-203',
    questionCode: 'Q000203',
    orderNumber: 3,
    questionText: 'Who holds the record for the fastest goal ever scored in FIFA World Cup history (10.8 seconds)?',
    questionAmharic: 'በዓለም ዋንጫ ታሪክ ውስጥ በ10.8 ሰከንድ ፈጣኑን ጎል ያስቆጠረው ተጫዋች ማን ነው?',
    options: ['Hakan Şükür', 'Bryan Robson', 'Clint Dempsey', 'Christian Benteke'],
    correctOptionIndex: 0,
    difficulty: 'EXPERT',
    category: 'World Cup',
    status: 'PUBLISHED',
    pool: 'DAILY_CHALLENGE',
    imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Ball kick off spot on pitch',
    sourceReference: 'FIFA Guinness World Record Audit 2002',
    explanation: 'Turkish striker Hakan Şükür scored after just 10.8 seconds against South Korea in the 2002 3rd-place match.',
    createdAt: '2026-08-29T11:30:00Z',
    updatedAt: '2026-09-23T09:10:00Z',
    updatedBy: 'Dawit Mengistu',
  },
  {
    id: 'q-204',
    questionCode: 'Q000204',
    orderNumber: 4,
    questionText: 'Which club won the 2021 Ethiopian Premier League title under coach Seyoum Kebede?',
    questionAmharic: 'በ2021 የኢትዮጵያ ፕሪሚየር ሊግ ዋንጫን ያነሳው የጎንደሩ ክለብ የትኛው ነው?',
    options: ['Fasil Kenema SC', 'Bahir Dar Kenema', 'Saint George SC', 'Sidama Coffee'],
    correctOptionIndex: 0,
    difficulty: 'MEDIUM',
    category: 'Ethiopian Football',
    status: 'PUBLISHED',
    pool: 'DAILY_CHALLENGE',
    imageUrl: undefined, // NO IMAGE test
    imageAlt: undefined,
    sourceReference: 'EPL Official Standings 2020-21',
    explanation: 'Fasil Kenema (The Emperors) clinched their historic maiden Ethiopian Premier League title in 2020-21.',
    createdAt: '2026-08-30T13:00:00Z',
    updatedAt: '2026-09-23T09:30:00Z',
    updatedBy: 'Dawit Mengistu',
  },

  // DRAFT Questions
  {
    id: 'q-301',
    questionCode: 'Q000301',
    levelNumber: 4,
    orderNumber: 1,
    questionText: 'What is the official home ground of Ethiopian Coffee SC (Bunna) in Addis Ababa?',
    questionAmharic: 'የኢትዮጵያ ቡና የእግር ኳስ ክለብ ዋና ሜዳ የቱ ነው?',
    options: ['Addis Ababa Stadium', 'Abebe Bikila Stadium', 'Bahir Dar International Stadium', 'Hawassa Stadium'],
    correctOptionIndex: 1,
    difficulty: 'EASY',
    category: 'Clubs',
    status: 'DRAFT',
    pool: 'LEVEL_BASED',
    imageUrl: undefined, // NO IMAGE test
    imageAlt: undefined,
    sourceReference: 'Addis Ababa Sports Commission Directory',
    explanation: 'Ethiopian Coffee SC has regularly used Abebe Bikila Stadium and Addis Ababa Stadium as home grounds.',
    createdAt: '2026-09-18T14:00:00Z',
    updatedAt: '2026-09-24T10:00:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-302',
    questionCode: 'Q000302',
    orderNumber: 5,
    questionText: 'How many total substitutions are allowed per team in standard 90-minute FIFA competitive matches since 2022?',
    questionAmharic: 'ከ2022 ጀምሮ በፊፋ መደበኛ 90 ደቂቃ ጨዋታ ላይ ስንት ተጫዋቾችን መቀየር ይቻላል?',
    options: ['3 substitutions', '4 substitutions', '5 substitutions', '6 substitutions'],
    correctOptionIndex: 2,
    difficulty: 'EASY',
    category: 'General Football',
    status: 'DRAFT',
    pool: 'DAILY_CHALLENGE',
    imageUrl: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Referee substitution board on sideline',
    sourceReference: 'IFAB Laws of the Game 2022/23 Law 3',
    explanation: 'The International Football Association Board (IFAB) permanently ratified 5 substitutions in 3 stoppage windows.',
    createdAt: '2026-09-19T11:00:00Z',
    updatedAt: '2026-09-24T11:30:00Z',
    updatedBy: 'Selamawit Desta',
  },
  {
    id: 'q-303',
    questionCode: 'Q000303',
    levelNumber: 12,
    orderNumber: 2,
    questionText: 'Which country hosted the Africa Cup of Nations (AFCON) in 2024 (awarded to Cote d\'Ivoire)?',
    questionAmharic: 'የ2023/24 የአፍሪካ ዋንጫን ያስተናገደችው የምዕራብ አፍሪካ ሀገር የትኛዋ ናት?',
    options: ['Senegal', 'Ivory Coast (Côte d\'Ivoire)', 'Morocco', 'Nigeria'],
    correctOptionIndex: 1,
    difficulty: 'MEDIUM',
    category: 'AFCON',
    status: 'DRAFT',
    pool: 'LEVEL_BASED',
    imageUrl: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Trophy ceremony in Abidjan',
    sourceReference: 'CAF TotalEnergies AFCON 2023 Official Report',
    explanation: 'Ivory Coast hosted the tournament and won the final 2-1 against Nigeria in Abidjan.',
    createdAt: '2026-09-20T16:00:00Z',
    updatedAt: '2026-09-24T14:20:00Z',
    updatedBy: 'Dawit Mengistu',
  },

  // NEEDS REVIEW Questions
  {
    id: 'q-401',
    questionCode: 'Q000401',
    levelNumber: 5,
    orderNumber: 1,
    questionText: 'Which legendary Ethiopian striker was nicknamed "The Black Diamond" and played in Italian Serie A for Torino in the 1960s?',
    questionAmharic: 'በ1960ዎቹ በጣሊያን ሴሪ ኤ ለቶሪኖ ተጫውቶ የነበረው ታዋቂው ኢትዮጵያዊ አጥቂ ማን ነበር?',
    options: ['Luciano Vassallo', 'Mengistu Worku', 'Italo Vassallo', 'Getachew Wolde'],
    correctOptionIndex: 1,
    difficulty: 'HARD',
    category: 'Ethiopian Football',
    status: 'NEEDS_REVIEW',
    pool: 'LEVEL_BASED',
    imageUrl: undefined, // NO IMAGE test
    imageAlt: undefined,
    sourceReference: 'Walia Historical Archive 1962 AFCON Legends',
    explanation: 'Mengistu Worku led Ethiopia to the 1962 AFCON trophy and is regarded as one of Ethiopia\'s greatest football icons.',
    createdAt: '2026-09-21T09:00:00Z',
    updatedAt: '2026-09-25T08:00:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-402',
    questionCode: 'Q000402',
    orderNumber: 6,
    questionText: 'Who holds the record for the most goals in a single UEFA Champions League season (17 goals in 2013-14)?',
    questionAmharic: 'በአንድ የሻምፒዮንስ ሊግ የውድድር ዘመን 17 ግቦችን በማስቆጠር ከፍተኛ ክብረወሰን የያዘው ተጫዋች ማን ነው?',
    options: ['Cristiano Ronaldo', 'Lionel Messi', 'Robert Lewandowski', 'Erling Haaland'],
    correctOptionIndex: 0,
    difficulty: 'MEDIUM',
    category: 'Champions League',
    status: 'NEEDS_REVIEW',
    pool: 'DAILY_CHALLENGE',
    imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Cristiano Ronaldo celebration in Lisbon final',
    sourceReference: 'UEFA Champions League Statistics 2013-14',
    explanation: 'Cristiano Ronaldo scored 17 goals as Real Madrid clinched "La Décima" in 2013-14.',
    createdAt: '2026-09-21T11:30:00Z',
    updatedAt: '2026-09-25T09:15:00Z',
    updatedBy: 'Selamawit Desta',
  },
  {
    id: 'q-403',
    questionCode: 'Q000403',
    levelNumber: 15,
    orderNumber: 3,
    questionText: 'What is the minimum diameter of a standard FIFA size 5 regulation football?',
    questionAmharic: 'የፊፋ ደረጃውን የጠበቀ ቁጥር 5 ኳስ ክብደት እና ዙሪያ ምን ያህል መሆን አለበት?',
    options: ['65 cm', '68 cm', '71 cm', '74 cm'],
    correctOptionIndex: 1,
    difficulty: 'EXPERT',
    category: 'General Football',
    status: 'NEEDS_REVIEW',
    pool: 'LEVEL_BASED',
    imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Regulation match football on white line',
    sourceReference: 'IFAB Law 2 - The Ball Specifications',
    explanation: 'According to Law 2, a size 5 ball must have a circumference between 68 cm (27 ins) and 70 cm (28 ins).',
    createdAt: '2026-09-22T14:00:00Z',
    updatedAt: '2026-09-25T11:00:00Z',
    updatedBy: 'Dawit Mengistu',
  },

  // INACTIVE Questions
  {
    id: 'q-501',
    questionCode: 'Q000501',
    levelNumber: 2,
    orderNumber: 8,
    questionText: 'Which stadium in South Africa hosted the 2010 FIFA World Cup Final between Spain and Netherlands?',
    questionAmharic: 'የ2010 የዓለም ዋንጫ ፍፃሜ ጨዋታ የተካሄደበት የደቡብ አፍሪካ ስታዲየም የትኛው ነው?',
    options: ['FNB Stadium (Soccer City)', 'Ellis Park Stadium', 'Moses Mabhida Stadium', 'Green Point Stadium'],
    correctOptionIndex: 0,
    difficulty: 'MEDIUM',
    category: 'World Cup',
    status: 'INACTIVE',
    pool: 'LEVEL_BASED',
    imageUrl: undefined, // NO IMAGE test
    imageAlt: undefined,
    sourceReference: 'FIFA World Cup South Africa 2010 Technical Review',
    explanation: 'The final was played at Soccer City (FNB Stadium) in Johannesburg where Andrés Iniesta scored the 116th minute winner.',
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-09-15T09:00:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-502',
    questionCode: 'Q000502',
    orderNumber: 12,
    questionText: 'Which club won the Premier League title without losing a single game ("The Invincibles") in 2003-04?',
    questionAmharic: 'በ2003-04 የውድድር ዘመን በአንድም ጨዋታ ሳይሸነፍ የፕሪሚየር ሊጉን ዋንጫ ያነሳው ቡድን ማን ነው?',
    options: ['Arsenal FC', 'Manchester United', 'Chelsea FC', 'Liverpool FC'],
    correctOptionIndex: 0,
    difficulty: 'EASY',
    category: 'Premier League',
    status: 'INACTIVE',
    pool: 'DAILY_CHALLENGE',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Highbury arena historic memory',
    sourceReference: 'Premier League Hall of Fame 2004',
    explanation: 'Arsène Wenger\'s Arsenal finished the 38-game season with 26 wins, 12 draws, and 0 losses.',
    createdAt: '2026-08-12T13:00:00Z',
    updatedAt: '2026-09-16T12:00:00Z',
    updatedBy: 'Abebe Tekele',
  },

  // Additional varied questions to test 50k scaling UI & filters
  {
    id: 'q-601',
    questionCode: 'Q000601',
    levelNumber: 1,
    orderNumber: 6,
    questionText: 'Who was named FIFA World Player of the Year three times and led Brazil to the 2002 World Cup with 8 goals?',
    questionAmharic: 'ብራዚልን ለ2002 የዓለም ዋንጫ ድል የመራው ድንቅ አጥቂ ማን ነው?',
    options: ['Ronaldo Nazário', 'Ronaldinho', 'Rivaldo', 'Romário'],
    correctOptionIndex: 0,
    difficulty: 'EASY',
    category: 'Players',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Ronaldo striking in Yokohama final',
    sourceReference: 'FIFA Player of the Century & 2002 Finals Record',
    explanation: 'Ronaldo "El Fenomeno" scored both goals in the 2-0 final against Germany.',
    createdAt: '2026-08-14T11:00:00Z',
    updatedAt: '2026-09-20T15:00:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-602',
    questionCode: 'Q000602',
    levelNumber: 2,
    orderNumber: 4,
    questionText: 'Which Ethiopian city is home to Fasil Kenema Football Club?',
    questionAmharic: 'የፋሲል ከነማ እግር ኳስ ክለብ መነሻ ከተማ የትኛዋ ናት?',
    options: ['Gondar', 'Bahir Dar', 'Hawassa', 'Mekelle'],
    correctOptionIndex: 0,
    difficulty: 'EASY',
    category: 'Ethiopian Football',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: undefined, // NO IMAGE test
    imageAlt: undefined,
    sourceReference: 'Ethiopian Premier League City Registry',
    explanation: 'Fasil Kenema is based in the historic castle city of Gondar.',
    createdAt: '2026-08-14T12:00:00Z',
    updatedAt: '2026-09-20T16:00:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-603',
    questionCode: 'Q000603',
    levelNumber: 5,
    orderNumber: 2,
    questionText: 'Which club won the very first European Cup in 1956 defeating Reims 4-3 in Paris?',
    questionAmharic: 'በ1956 የተደረገውን የመጀመሪያውን የአውሮፓ ዋንጫ ፍፃሜ ያሸነፈው ክለብ ማን ነው?',
    options: ['Real Madrid', 'Benfica', 'Stade de Reims', 'Inter Milan'],
    correctOptionIndex: 0,
    difficulty: 'HARD',
    category: 'Champions League',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Historic trophy and silver cup celebration',
    sourceReference: 'UEFA 50-Year Jubilee History 1956-2006',
    explanation: 'Real Madrid won the first five European Cups in succession from 1956 to 1960.',
    createdAt: '2026-08-16T15:00:00Z',
    updatedAt: '2026-09-21T10:00:00Z',
    updatedBy: 'Selamawit Desta',
  },
  {
    id: 'q-604',
    questionCode: 'Q000604',
    orderNumber: 7,
    questionText: 'What is the maximum regulation time of each extra time half during knockout tournaments?',
    questionAmharic: 'በመደበኛ ውድድሮች ተጨማሪ ሰዓት (Extra Time) እያንዳንዳቸው ግማሾች ስንት ደቂቃ ናቸው?',
    options: ['10 minutes', '15 minutes', '20 minutes', '25 minutes'],
    correctOptionIndex: 1,
    difficulty: 'EASY',
    category: 'General Football',
    status: 'PUBLISHED',
    pool: 'DAILY_CHALLENGE',
    imageUrl: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Match time tracking and referee watch',
    sourceReference: 'IFAB Law 7 - The Duration of the Match',
    explanation: 'Extra time consists of two equal halves of 15 minutes each.',
    createdAt: '2026-08-18T10:00:00Z',
    updatedAt: '2026-09-22T08:30:00Z',
    updatedBy: 'Dawit Mengistu',
  },
  {
    id: 'q-605',
    questionCode: 'Q000605',
    levelNumber: 8,
    orderNumber: 1,
    questionText: 'Which club did Lionel Messi play for during his senior professional debut in 2004?',
    questionAmharic: 'ሊዮኔል ሜሲ በ2004 ዓ.ም. ለመጀመሪያ ጊዜ ፕሮፌሽናል ጨዋታውን ያደረገው ለየትኛው ክለብ ነው?',
    options: ['FC Barcelona', 'Newell\'s Old Boys', 'Paris Saint-Germain', 'Inter Miami'],
    correctOptionIndex: 0,
    difficulty: 'EASY',
    category: 'Players',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: undefined, // NO IMAGE test
    imageAlt: undefined,
    sourceReference: 'FC Barcelona La Masia & First Team Records',
    explanation: 'Messi made his league debut against Espanyol on October 16, 2004, at age 17.',
    createdAt: '2026-08-20T12:00:00Z',
    updatedAt: '2026-09-23T11:00:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-606',
    questionCode: 'Q000606',
    orderNumber: 8,
    questionText: 'Who scored the winning goal in the 2010 FIFA World Cup Final in extra time for Spain?',
    questionAmharic: 'በ2010 የዓለም ዋንጫ ፍፃሜ ላይ ለስፔን አሸናፊዋን ጎል ያስቆጠረው ተጫዋች ማን ነው?',
    options: ['Xavi Hernández', 'Andrés Iniesta', 'Fernando Torres', 'David Villa'],
    correctOptionIndex: 1,
    difficulty: 'MEDIUM',
    category: 'World Cup',
    status: 'PUBLISHED',
    pool: 'DAILY_CHALLENGE',
    imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Iniesta goal celebration in Johannesburg',
    sourceReference: 'FIFA World Cup 2010 Official Match Report #64',
    explanation: 'Andrés Iniesta struck in the 116th minute to deliver Spain\'s first FIFA World Cup title.',
    createdAt: '2026-08-22T13:00:00Z',
    updatedAt: '2026-09-23T12:00:00Z',
    updatedBy: 'Dawit Mengistu',
  },
  {
    id: 'q-607',
    questionCode: 'Q000607',
    levelNumber: 10,
    orderNumber: 1,
    questionText: 'Which African nation reached the quarter-finals of the 1990 FIFA World Cup in Italy powered by Roger Milla?',
    questionAmharic: 'በ1990 የጣሊያን የዓለም ዋንጫ ላይ በሮጀር ሚላ አስደናቂ ብቃት ሩብ ፍፃሜ የደረሰችው አፍሪካዊት ሀገር ማን ናት?',
    options: ['Cameroon (Indomitable Lions)', 'Egypt', 'Nigeria', 'Morocco'],
    correctOptionIndex: 0,
    difficulty: 'MEDIUM',
    category: 'International Football',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: undefined, // NO IMAGE test
    imageAlt: undefined,
    sourceReference: 'FIFA Italia 90 Retrospective',
    explanation: 'Cameroon defeated reigning champions Argentina in the opener and reached the quarter-finals against England.',
    createdAt: '2026-08-24T10:00:00Z',
    updatedAt: '2026-09-24T09:00:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-608',
    questionCode: 'Q000608',
    levelNumber: 25,
    orderNumber: 1,
    questionText: 'Who is the all-time top scorer in the UEFA Champions League tournament with over 140 goals?',
    questionAmharic: 'በአውሮፓ ሻምፒዮንስ ሊግ ታሪክ ውስጥ ከ140 በላይ ጎሎችን በማስቆጠር የሁልጊዜ ከፍተኛ ጎል አስቆጣሪ ማን ነው?',
    options: ['Lionel Messi', 'Cristiano Ronaldo', 'Robert Lewandowski', 'Raúl González'],
    correctOptionIndex: 1,
    difficulty: 'MEDIUM',
    category: 'Champions League',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Champions League European arena nights',
    sourceReference: 'UEFA.com All-Time Top Scorers Official Data',
    explanation: 'Cristiano Ronaldo scored 140 goals across spells at Manchester United, Real Madrid, and Juventus.',
    createdAt: '2026-08-25T11:00:00Z',
    updatedAt: '2026-09-24T10:00:00Z',
    updatedBy: 'Selamawit Desta',
  },
  {
    id: 'q-609',
    questionCode: 'Q000609',
    orderNumber: 9,
    questionText: 'What is the distance in yards (or meters) from the goal line to the penalty spot in association football?',
    questionAmharic: 'ከግብ መስመር እስከ ፍፁም ቅጣት ምት (Penalty) ነጥብ ያለው ርቀት ስንት ሜትር ነው?',
    options: ['10 yards (9.15 m)', '12 yards (11 m)', '14 yards (12.8 m)', '16 yards (14.6 m)'],
    correctOptionIndex: 1,
    difficulty: 'EASY',
    category: 'General Football',
    status: 'PUBLISHED',
    pool: 'DAILY_CHALLENGE',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Penalty spot and penalty box markings',
    sourceReference: 'IFAB Law 1 - The Field of Play',
    explanation: 'The penalty mark is placed 12 yards (11 meters) from the midpoint between the goalposts.',
    createdAt: '2026-08-26T12:00:00Z',
    updatedAt: '2026-09-24T11:00:00Z',
    updatedBy: 'Dawit Mengistu',
  },
  {
    id: 'q-610',
    questionCode: 'Q000610',
    levelNumber: 50,
    orderNumber: 1,
    questionText: 'Which club won the historic "Treble" (Premier League, FA Cup, UEFA Champions League) in 1999 under Sir Alex Ferguson?',
    questionAmharic: 'በ1999 ሶስቱን ዋና ዋና ዋንጫዎች (Treble) ያነሳው የእንግሊዝ ታላቅ ክለብ ማን ነው?',
    options: ['Manchester United', 'Liverpool FC', 'Arsenal FC', 'Manchester City'],
    correctOptionIndex: 0,
    difficulty: 'MEDIUM',
    category: 'Premier League',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: undefined, // NO IMAGE test
    imageAlt: undefined,
    sourceReference: 'English Football Hall of Fame 1999 Season',
    explanation: 'Manchester United completed the Treble with a stoppage-time comeback against Bayern Munich at the Camp Nou.',
    createdAt: '2026-08-27T14:00:00Z',
    updatedAt: '2026-09-24T12:00:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-611',
    questionCode: 'Q000611',
    levelNumber: 1,
    orderNumber: 7,
    questionText: 'Which country has won the most FIFA Men\'s World Cup tournaments in history (5 titles)?',
    questionAmharic: 'በዓለም ዋንጫ ታሪክ ውስጥ አምስት ጊዜ ዋንጫ በማንሳት ቀዳሚ የሆነችው ሀገር ማን ናት?',
    options: ['Germany', 'Italy', 'Brazil', 'Argentina'],
    correctOptionIndex: 2,
    difficulty: 'EASY',
    category: 'World Cup',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=600&q=80',
    imageAlt: 'Pentacampeão trophy celebration',
    sourceReference: 'FIFA World Cup Roll of Honour',
    explanation: 'Brazil won the World Cup in 1958, 1962, 1970, 1994, and 2002.',
    createdAt: '2026-08-28T15:00:00Z',
    updatedAt: '2026-09-24T13:00:00Z',
    updatedBy: 'Abebe Tekele',
  },
  {
    id: 'q-612',
    questionCode: 'Q000612',
    levelNumber: 4,
    orderNumber: 2,
    questionText: 'What color cards does a referee carry to indicate caution and sending-off in association football?',
    questionAmharic: 'የእግር ኳስ ዋና ዳኛ ተጫዋቾችን ለማስጠንቀቅ እና ለማባረር የሚጠቀማቸው ካርዶች ቀለማቸው ምን ምን ነው?',
    options: ['Yellow and Red', 'Blue and Red', 'Yellow and Black', 'Green and Red'],
    correctOptionIndex: 0,
    difficulty: 'EASY',
    category: 'General Football',
    status: 'PUBLISHED',
    pool: 'LEVEL_BASED',
    imageUrl: undefined, // NO IMAGE test
    imageAlt: undefined,
    sourceReference: 'IFAB Law 12 - Fouls and Misconduct',
    explanation: 'Yellow and Red cards were invented by English referee Ken Aston and introduced at the 1970 World Cup.',
    createdAt: '2026-08-29T09:00:00Z',
    updatedAt: '2026-09-24T14:00:00Z',
    updatedBy: 'Selamawit Desta',
  }
];

export const CATEGORY_OPTIONS = [
  'All',
  'World Cup',
  'AFCON',
  'Premier League',
  'Champions League',
  'International Football',
  'Ethiopian Football',
  'Players',
  'Clubs',
  'History',
  'General Football',
];

export const DIFFICULTY_OPTIONS = [
  'All',
  'Easy',
  'Medium',
  'Hard',
  'Expert',
];
